// Code generated by the Encore 1.48.1 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly cart: cart.ServiceClient
    public readonly category: category.ServiceClient
    public readonly order: order.ServiceClient
    public readonly payment: payment.ServiceClient
    public readonly product: product.ServiceClient
    public readonly review: review.ServiceClient
    public readonly search: search.ServiceClient
    public readonly store: store.ServiceClient
    public readonly user: user.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.cart = new cart.ServiceClient(base)
        this.category = new category.ServiceClient(base)
        this.order = new order.ServiceClient(base)
        this.payment = new payment.ServiceClient(base)
        this.product = new product.ServiceClient(base)
        this.review = new review.ServiceClient(base)
        this.search = new search.ServiceClient(base)
        this.store = new store.ServiceClient(base)
        this.user = new user.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { addItem as api_cart_add_item_addItem } from "~backend/cart/add_item";
import { get as api_cart_get_get } from "~backend/cart/get";

export namespace cart {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addItem = this.addItem.bind(this)
            this.get = this.get.bind(this)
        }

        /**
         * Adds an item to the cart.
         */
        public async addItem(params: RequestType<typeof api_cart_add_item_addItem>): Promise<ResponseType<typeof api_cart_add_item_addItem>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cart/items`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cart_add_item_addItem>
        }

        /**
         * Retrieves a cart by session ID.
         */
        public async get(params: { sessionId: string }): Promise<ResponseType<typeof api_cart_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cart/${encodeURIComponent(params.sessionId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cart_get_get>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_category_create_create } from "~backend/category/create";
import { list as api_category_list_list } from "~backend/category/list";

export namespace category {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.list = this.list.bind(this)
        }

        /**
         * Creates a new category.
         */
        public async create(params: RequestType<typeof api_category_create_create>): Promise<ResponseType<typeof api_category_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/categories`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_category_create_create>
        }

        /**
         * Retrieves all categories with hierarchical structure.
         */
        public async list(): Promise<ResponseType<typeof api_category_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/categories`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_category_list_list>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_order_create_create } from "~backend/order/create";
import { get as api_order_get_get } from "~backend/order/get";
import { listByStore as api_order_list_by_store_listByStore } from "~backend/order/list_by_store";
import { update as api_order_update_update } from "~backend/order/update";

export namespace order {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
            this.listByStore = this.listByStore.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new order.
         */
        public async create(params: RequestType<typeof api_order_create_create>): Promise<ResponseType<typeof api_order_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/orders`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_order_create_create>
        }

        /**
         * Retrieves an order by ID.
         */
        public async get(params: { id: number }): Promise<ResponseType<typeof api_order_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/orders/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_order_get_get>
        }

        /**
         * Retrieves all orders for a specific store.
         */
        public async listByStore(params: { storeId: number }): Promise<ResponseType<typeof api_order_list_by_store_listByStore>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/orders/store/${encodeURIComponent(params.storeId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_order_list_by_store_listByStore>
        }

        /**
         * Updates an order's status or payment information.
         */
        public async update(params: RequestType<typeof api_order_update_update>): Promise<ResponseType<typeof api_order_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                status:                params.status,
                stripePaymentIntentId: params.stripePaymentIntentId,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/orders/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_order_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { cancelSubscription as api_payment_cancel_subscription_cancelSubscription } from "~backend/payment/cancel_subscription";
import { confirmPayment as api_payment_confirm_payment_confirmPayment } from "~backend/payment/confirm_payment";
import { createPaymentIntent as api_payment_create_payment_intent_createPaymentIntent } from "~backend/payment/create_payment_intent";
import { createSubscription as api_payment_create_subscription_createSubscription } from "~backend/payment/create_subscription";

export namespace payment {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.cancelSubscription = this.cancelSubscription.bind(this)
            this.confirmPayment = this.confirmPayment.bind(this)
            this.createPaymentIntent = this.createPaymentIntent.bind(this)
            this.createSubscription = this.createSubscription.bind(this)
        }

        /**
         * Cancels a Stripe subscription.
         */
        public async cancelSubscription(params: RequestType<typeof api_payment_cancel_subscription_cancelSubscription>): Promise<ResponseType<typeof api_payment_cancel_subscription_cancelSubscription>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/payment/subscription/cancel`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_payment_cancel_subscription_cancelSubscription>
        }

        /**
         * Confirms a payment and updates the order status.
         */
        public async confirmPayment(params: RequestType<typeof api_payment_confirm_payment_confirmPayment>): Promise<ResponseType<typeof api_payment_confirm_payment_confirmPayment>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/payment/confirm`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_payment_confirm_payment_confirmPayment>
        }

        /**
         * Creates a Stripe payment intent for an order.
         */
        public async createPaymentIntent(params: RequestType<typeof api_payment_create_payment_intent_createPaymentIntent>): Promise<ResponseType<typeof api_payment_create_payment_intent_createPaymentIntent>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/payment/intent`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_payment_create_payment_intent_createPaymentIntent>
        }

        /**
         * Creates a Stripe subscription for a user.
         */
        public async createSubscription(params: RequestType<typeof api_payment_create_subscription_createSubscription>): Promise<ResponseType<typeof api_payment_create_subscription_createSubscription>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/payment/subscription`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_payment_create_subscription_createSubscription>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_product_create_create } from "~backend/product/create";
import { deleteProduct as api_product_delete_deleteProduct } from "~backend/product/delete";
import { get as api_product_get_get } from "~backend/product/get";
import { listActiveByStore as api_product_list_active_by_store_listActiveByStore } from "~backend/product/list_active_by_store";
import { listByStore as api_product_list_by_store_listByStore } from "~backend/product/list_by_store";
import { update as api_product_update_update } from "~backend/product/update";

export namespace product {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.deleteProduct = this.deleteProduct.bind(this)
            this.get = this.get.bind(this)
            this.listActiveByStore = this.listActiveByStore.bind(this)
            this.listByStore = this.listByStore.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new product for a store.
         */
        public async create(params: RequestType<typeof api_product_create_create>): Promise<ResponseType<typeof api_product_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/products`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_product_create_create>
        }

        /**
         * Deletes a product.
         */
        public async deleteProduct(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/products/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Retrieves a product by ID.
         */
        public async get(params: { id: number }): Promise<ResponseType<typeof api_product_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/products/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_product_get_get>
        }

        /**
         * Retrieves all active products for a specific store (public endpoint).
         */
        public async listActiveByStore(params: { storeId: number }): Promise<ResponseType<typeof api_product_list_active_by_store_listActiveByStore>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/products/store/${encodeURIComponent(params.storeId)}/active`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_product_list_active_by_store_listActiveByStore>
        }

        /**
         * Retrieves all products for a specific store.
         */
        public async listByStore(params: { storeId: number }): Promise<ResponseType<typeof api_product_list_by_store_listByStore>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/products/store/${encodeURIComponent(params.storeId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_product_list_by_store_listByStore>
        }

        /**
         * Updates a product's information.
         */
        public async update(params: RequestType<typeof api_product_update_update>): Promise<ResponseType<typeof api_product_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                attributes:        params.attributes,
                brand:             params.brand,
                categoryId:        params.categoryId,
                description:       params.description,
                dimensions:        params.dimensions,
                discountEndDate:   params.discountEndDate,
                discountStartDate: params.discountStartDate,
                discountType:      params.discountType,
                discountValue:     params.discountValue,
                featured:          params.featured,
                imageUrl:          params.imageUrl,
                images:            params.images,
                inventory:         params.inventory,
                isActive:          params.isActive,
                maxOrderQuantity:  params.maxOrderQuantity,
                metaDescription:   params.metaDescription,
                metaTitle:         params.metaTitle,
                minOrderQuantity:  params.minOrderQuantity,
                name:              params.name,
                price:             params.price,
                seoKeywords:       params.seoKeywords,
                shippingClass:     params.shippingClass,
                sku:               params.sku,
                status:            params.status,
                tags:              params.tags,
                variants:          params.variants,
                weight:            params.weight,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/products/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_product_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_review_create_create } from "~backend/review/create";
import { listByProduct as api_review_list_by_product_listByProduct } from "~backend/review/list_by_product";

export namespace review {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.listByProduct = this.listByProduct.bind(this)
        }

        /**
         * Creates a new product review.
         */
        public async create(params: RequestType<typeof api_review_create_create>): Promise<ResponseType<typeof api_review_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/reviews`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_review_create_create>
        }

        /**
         * Retrieves all approved reviews for a product.
         */
        public async listByProduct(params: { productId: number }): Promise<ResponseType<typeof api_review_list_by_product_listByProduct>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/reviews/product/${encodeURIComponent(params.productId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_review_list_by_product_listByProduct>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { search as api_search_search_search } from "~backend/search/search";

export namespace search {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.search = this.search.bind(this)
        }

        /**
         * Performs a full-text search across products, stores, and categories.
         */
        public async search(params: RequestType<typeof api_search_search_search>): Promise<ResponseType<typeof api_search_search_search>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/search`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_search_search_search>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_store_create_create } from "~backend/store/create";
import { get as api_store_get_get } from "~backend/store/get";
import { getBySlug as api_store_get_by_slug_getBySlug } from "~backend/store/get_by_slug";
import { listByUser as api_store_list_by_user_listByUser } from "~backend/store/list_by_user";
import { update as api_store_update_update } from "~backend/store/update";

export namespace store {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
            this.getBySlug = this.getBySlug.bind(this)
            this.listByUser = this.listByUser.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new store for a user.
         */
        public async create(params: RequestType<typeof api_store_create_create>): Promise<ResponseType<typeof api_store_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/stores`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_store_create_create>
        }

        /**
         * Retrieves a store by ID.
         */
        public async get(params: { id: number }): Promise<ResponseType<typeof api_store_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/stores/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_store_get_get>
        }

        /**
         * Retrieves a store by slug.
         */
        public async getBySlug(params: { slug: string }): Promise<ResponseType<typeof api_store_get_by_slug_getBySlug>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/stores/slug/${encodeURIComponent(params.slug)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_store_get_by_slug_getBySlug>
        }

        /**
         * Retrieves all stores for a specific user.
         */
        public async listByUser(params: { userId: number }): Promise<ResponseType<typeof api_store_list_by_user_listByUser>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/stores/user/${encodeURIComponent(params.userId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_store_list_by_user_listByUser>
        }

        /**
         * Updates a store's information.
         */
        public async update(params: RequestType<typeof api_store_update_update>): Promise<ResponseType<typeof api_store_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                description: params.description,
                domain:      params.domain,
                isActive:    params.isActive,
                logoUrl:     params.logoUrl,
                name:        params.name,
                slug:        params.slug,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/stores/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_store_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_user_create_create } from "~backend/user/create";
import { get as api_user_get_get } from "~backend/user/get";
import { list as api_user_list_list } from "~backend/user/list";
import { update as api_user_update_update } from "~backend/user/update";

export namespace user {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new user account.
         */
        public async create(params: RequestType<typeof api_user_create_create>): Promise<ResponseType<typeof api_user_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_create_create>
        }

        /**
         * Retrieves a user by ID.
         */
        public async get(params: { id: number }): Promise<ResponseType<typeof api_user_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_get_get>
        }

        /**
         * Retrieves all users (admin only).
         */
        public async list(): Promise<ResponseType<typeof api_user_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_list_list>
        }

        /**
         * Updates a user's information.
         */
        public async update(params: RequestType<typeof api_user_update_update>): Promise<ResponseType<typeof api_user_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                name:               params.name,
                stripeCustomerId:   params.stripeCustomerId,
                subscriptionId:     params.subscriptionId,
                subscriptionPlan:   params.subscriptionPlan,
                subscriptionStatus: params.subscriptionStatus,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_update_update>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.48.1)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET);
